language: bash
sudo: required
dist: xenial
services: docker
before_script:
- docker --version
script:
- docker build
  -t ev3dev/debian-stretch-cross
  -f ev3dev-stretch/debian-stretch-cross.dockerfile
  ev3dev-stretch
- docker build
  -t ev3dev/debian-buster-cross
  -f ev3dev-buster/debian-buster-cross.dockerfile
  ev3dev-buster
